name: Ayerlans
title: test title
description: god is in his heaven
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: evangelionleo@outlook.com
disqus_username: disqus_username
show_hero: true
menu:
  - title: Home
    url:http://www.ayerlans.cn/
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
